/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiagtBorder: typeof import('./src/components/aiagt/aiagt-border.vue')['default']
    AiagtLong: typeof import('./src/components/aiagt/aiagt-long.vue')['default']
    AiagtText: typeof import('./src/components/aiagt/aiagt-text.vue')['default']
    Editor: typeof import('./src/components/editor/editor.vue')['default']
    Input: typeof import('./src/components/input/input.vue')['default']
    InputGroup: typeof import('./src/components/input-group/input-group.vue')['default']
    Modal: typeof import('./src/components/modal/modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/layout/home/components/search.vue')['default']
  }
}
